### PR TITLE
feat: export testing mocks for consumers

### PR DESCRIPTION
**Pull request by Blackbaud-ColbyWhite**

### CODE REVIEW

**Comment by Blackbaud-SteveBrush** [comment]
Looking at this now, I'm not even sure the way we are handling the mock modal service in the confirm specs is appropriate. I'll need to rework these tests to figure out what's the best, prescribed method for mocking out the services. In the meantime, you can easily mock out the service this way:

```
TestBed.configureTestingModule({
  providers: [
    { provide: SkyModalService, useClass: MyMockModalService }
  ]
});
```

**Comment by Blackbaud-ColbyWhite** [comment]
@Blackbaud-SteveBrush , in your example it looks like the consumer would be making their own `MyMockModalService`. my goal is specifically to not have every consumer making their own `MyMockModalService` and instead, we all j/ use the one that's in here.

**Comment by Blackbaud-DiHuynh** [comment]
@Blackbaud-SteveBrush what do you think about @Blackbaud-ColbyWhite 's comment? if so, is there any chance we can move this PR forward?

**Comment by Blackbaud-ColbyWhite** [comment]
I think blackbaud/skyux-sdk-testing#23 removes the need/desire for this.

**Pull request closed without merging**
